name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: dekel5030
          outputs: dist/snake.svg

      - name: Publish SVG to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
          destination_dir: .
          commit_message: "chore: update snake"
